name: Test

on:
   push:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v2
           with:
              fetch-depth: 0

         - name: Use Node.js 14.15.5
           uses: actions/setup-node@v1
           with:
              node-version: 14.x

         - name: Install decencies
           run: yarn
         
         - name: Check linting
           run: yarn lint